# 1. Tipo de base de dados
quarkus.datasource.db-kind=postgresql

# 2. Credenciais de acesso (Lê do Render ou usa o padrão local caso não existam)
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:1234}

# 3. URL de conexão JDBC
quarkus.datasource.jdbc.url=jdbc:${DB_URL:postgresql://localhost:5432/site-blog}

# 4. Estratégia de geração das tabelas (Hibernate ORM)
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true
quarkus.datasource.devservices.enabled=false

# 5. Para VALIDAR o token (Lê a chave pública padrão que foi enviada ao GitHub)
smallrye.jwt.token.cookie=meu_token_jwt
mp.jwt.verify.publickey.location=publicKey.pem
# O emissor do token em produção deve ser dinâmico para aceitar o URL do Render
mp.jwt.verify.issuer=${JWT_ISSUER:http://localhost:8080}
mp.jwt.token.header=Cookie

# 6. Para CRIAR o token (Procura o ficheiro no caminho definido pela variável)
smallrye.jwt.sign.key.location=${JWT_KEY_LOCATION:privateKey-pkcs8.pem}

# Configuração extra para otimização do build no Render
quarkus.package.type=fast-jar