# 1. Tipo do banco de dados (Ex: postgresql, mysql, h2)
quarkus.datasource.db-kind=postgresql

# 2. Credenciais de acesso
quarkus.datasource.username=postgres
quarkus.datasource.password=1234

# 3. URL de conexão JDBC
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/site-blog

# 4. Estratégia de geração das tabelas (Hibernate ORM)
# 'update' cria as tabelas automaticamente com base nas suas classes @Entity
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.format-sql=true

# IMPORTANTE: Desativa o banco automático do Quarkus (Dev Services)
# para ele focar no seu banco local
quarkus.datasource.devservices.enabled=false
